### ISSUE TITLE
Where did the smiles of DUD-E for 3D-CNN come from?

### ISSUE THREAD

**Issue by 0ut0fcontrol** [rareylab/MLValidation#1]
Hi.
The input files of Grid-based 3D-CNN are in .smi format. Did they come from DUD-E .ism or converted from .mol2?
```bash
python grid_descriptor.py --input DUD_E/*/*.smi --output grid3Dmols
```

**Comment by JochenSieg** [comment]
Hi,
yes that is a typo. The .smi files are just the .ism files. They are just the actives_final.ism and decoys_final.ism for each target downloaded from http://dude.docking.org.

I fixed the typo
`python grid_descriptor.py --input DUD_E/*/*.ism --output grid3Dmols`

Thanks for pointing that out and sorry for the late response!
